package main

import (
	"fmt"
	"github.com/blang/semver"
	"time"
)

// NOTE: using blang/semver package, not golang/semver
// ties to https://docs.google.com/document/d/15pp3gZ4ipShEtLR89RKU7jthNBrX7x_384_xsVXtp_E/edit (RH Only)

func getTimeStamp() string {
	t := time.Now().In(time.UTC)
	return t.Format("20060102150405")
}

func main() {
	timestamp := getTimeStamp()

	latestVersion := "1.2.3-2"
	shouldBeLatestVersion := semver.MustParse(latestVersion)
	shouldBeOldestVersion := semver.MustParse("1.2.1")
	anAutoGeneratedPatchVersion := semver.MustParse(latestVersion + "-" + timestamp + "-patched")

	if shouldBeLatestVersion.GT(shouldBeOldestVersion) {
		fmt.Printf("shouldBeLatestVersion (%s) is GT shouldBeOldestVersion (%s)\n",
			shouldBeLatestVersion, shouldBeOldestVersion)
		if anAutoGeneratedPatchVersion.GT(shouldBeLatestVersion) {
			fmt.Printf("semver ordering is: \n%s\n%s\n%s\n",
				shouldBeOldestVersion, shouldBeLatestVersion, anAutoGeneratedPatchVersion)
		}
	}
}
